# Generated by Django 3.1.1 on 2020-10-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201014_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='post_img',
            field=models.ImageField(blank=True, null=True, upload_to='post_images'),
        ),
    ]
